// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import EntryGuidelineController from './entry_guideline_controller';
application.register('entry-guideline', EntryGuidelineController);

import FormPlayableTimesController from './form_playable_times_controller';
application.register('form-playable-times', FormPlayableTimesController);

import FormPlaysController from './form_plays_controller';
application.register('form-plays', FormPlaysController);
