inherit_from: https://raw.githubusercontent.com/cookpad/styleguide/master/.rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rubycw

Bundler/OrderedGems:
  Enabled: true

Layout/LineLength:
  Max: 160

Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Security:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

# rubocop-performance

Performance:
  Enabled: true

# rubocop-rails

Rails:
  Enabled: true

# rubocop-rspec

RSpec:
  Enabled: true

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true

# rubocop-rubycw

Rubycw:
  Enabled: true
