require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-graphql

AllCops:
  NewCops: enable

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin

Layout/LineLength:
  Max: 160

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - config/{application,boot,environment}.rb
    - config/environments/*.rb

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# rubocop-graphql

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/FieldDefinitions:
  Exclude:
    - app/graphql/types/query_type.rb

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

# rubocop-rails

Rails/EnvironmentVariableAccess:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

# rubocop-rspec

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 6 # default: 5

RSpec/NestedGroups:
  Max: 4

RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true
