require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rubycw

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 160

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# rubocop-rspec

RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 6 # default: 5

RSpec/NestedGroups:
  Max: 4

RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true
