inherit_from: https://raw.githubusercontent.com/cookpad/styleguide/master/.rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6

Style/MutableConstant:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

# rubocop-performance

Performance:
  Enabled: true

# rubocop-rails

Rails:
  Enabled: true

# rubocop-rspec

RSpec:
  Enabled: true
