sudo: required
dist: xenial

language: ruby

services:
  - postgresql

addons:
  chrome: stable

cache: bundler

bundler_args: --without development production

before_install:
  # Install Elasticsearch 6.x
  - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
  - sudo apt-get update && sudo apt-get install elasticsearch
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install --verbose --batch analysis-kuromoji
  - sudo service elasticsearch start
  # Update Bundler
  - gem install bundler

before_script:
  - sleep 10 # For Elasticsearch
  - cp config/database.yml.travis config/database.yml && bin/rails db:create

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5e88c507b05f867f94a
