dist: xenial

language: ruby

env:
  - ES_VERSION=6.2.4

services:
  - postgresql

addons:
  chrome: stable

cache: bundler

bundler_args: --without development production

before_install:
  # Install Elasticsearch
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch-plugin install --verbose --batch analysis-kuromoji
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  # Update Bundler
  - gem install bundler

before_script:
  - cp config/database.yml.travis config/database.yml && bin/rails db:create
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200 # Wait for Elasticsearch

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5e88c507b05f867f94a
