sudo: required
dist: trusty

language: ruby

services:
  - postgresql
  - elasticsearch

addons:
  chrome: stable

cache: bundler

bundler_args: --without development production

before_install:
  - gem install bundler

before_script:
  - sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install -b analysis-kuromoji
  - sudo service elasticsearch restart
  - cp config/database.yml.travis config/database.yml
  - bin/rails db:create
  - sleep 5 # https://docs.travis-ci.com/user/database-setup/#ElasticSearch

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5e88c507b05f867f94a
