name: 'LiveLog'

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SELENIUM_REMOTE: '1'

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres:
    image: postgres:18
    restart: unless-stopped
    network_mode: service:rails-app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  elasticsearch:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.elasticsearch
    restart: unless-stopped
    network_mode: service:rails-app
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped
    network_mode: service:rails-app
    # https://medium.com/the-curve-tech-blog/dealing-with-cryptic-selenium-webdriver-error-invalidsessioniderror-errors-9c15abc68fdf
    shm_size: 256mb

volumes:
  postgres-data:
  elasticsearch-data:
