services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: postgres
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vscode
      POSTGRES_PASSWORD: postgres
    network_mode: service:app

  elasticsearch:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.elasticsearch
    restart: unless-stopped
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    network_mode: service:app

volumes:
  postgres-data:
  elasticsearch-data:
