default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: LiveLog2_development

test:
  <<: *default
  database: LiveLog2_test

production:
  <<: *default
  database: LiveLog2_production
  username: LiveLog2
  password: <%= ENV['LIVELOG2_DATABASE_PASSWORD'] %>
