default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  database: livelog_development

test:
  <<: *default
  database: livelog_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
