name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'bin/*'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'bin/*'

jobs:
  RSpec:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:11.6
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      elasticsearch:
        image: elasticsearch:6.8.8
        ports:
          - 9200:9200
        options: --env "discovery.type=single-node" --health-cmd "curl http://localhost:9200/_cluster/health" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Bundler cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-

      - name: Get yarn cache dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache

      - name: Yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          sudo apt-get install libpq-dev
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3 --with=test
          yarn install

      - name: Setup database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rake db:create
          bin/rake ridgepole:apply

      - name: Run spec
        run: bin/rake spec

  RuboCop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-

      - name: Install dependencies
        run: |
          sudo apt-get install libpq-dev
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3 --with=test

      - name: Run rubocop
        run: bundle exec rubocop --parallel

  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - run: yarn install

      - run: yarn run eslint

