name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  RuboCop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .ruby-version
        run: echo "::set-output name=version::$(cat .ruby-version)"
        id: ruby-version

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.version }}

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          sudo apt install libpq-dev
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Run rubocop
        run: bundle exec rubocop --parallel

  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
        id: yarn-cache

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - run: yarn install

      - run: yarn run eslint

